apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-persistent-volume
spec:
  capacity:
    storage: 128M
  accessModes:
    # Only a single node can read the volume
    - ReadWriteOnce
  hostPath:
    # Path inside the cluster
    path: /data/demo-persistent-value